package reciter.engine.analysis.evidence;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;

import lombok.Data;
import lombok.ToString;
import reciter.engine.analysis.evidence.AffiliationEvidence.InstitutionalAffiliationMatchType;
import reciter.engine.analysis.evidence.AffiliationEvidence.InstitutionalAffiliationSource;

@Data
@ToString
@DynamoDBDocument
public class TargetAuthorScopusAffiliation {
	private InstitutionalAffiliationSource targetAuthorInstitutionalAffiliationSource;
	private String targetAuthorInstitutionalAffiliationIdentity;
	private String targetAuthorInstitutionalAffiliationArticleScopusLabel;
	private int targetAuthorInstitutionalAffiliationArticleScopusAffiliationId;
	private InstitutionalAffiliationMatchType targetAuthorInstitutionalAffiliationMatchType;
	private double targetAuthorInstitutionalAffiliationMatchTypeScore;
}
