package reciter.database.dynamodb;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.BeanCreationException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.type.filter.AnnotationTypeFilter;

import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import software.amazon.awssdk.http.apache.ApacheHttpClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.model.AttributeDefinition;
import software.amazon.awssdk.services.dynamodb.model.BillingMode;
import software.amazon.awssdk.services.dynamodb.model.CreateTableRequest;
import software.amazon.awssdk.services.dynamodb.model.DescribeTableRequest;
import software.amazon.awssdk.services.dynamodb.model.DescribeTableResponse;
import software.amazon.awssdk.services.dynamodb.model.DynamoDbException;
import software.amazon.awssdk.services.dynamodb.model.KeySchemaElement;
import software.amazon.awssdk.services.dynamodb.model.KeyType;
import software.amazon.awssdk.services.dynamodb.model.ListTablesResponse;
import software.amazon.awssdk.services.dynamodb.model.ProvisionedThroughput;
import software.amazon.awssdk.services.dynamodb.model.ScalarAttributeType;
import software.amazon.awssdk.services.dynamodb.model.TableStatus;


@Configuration
public class DynamoDbConfig {
	
	private static final Logger log = LoggerFactory.getLogger(DynamoDbConfig.class);

	private String amazonDynamoDBEndpoint = System.getenv("AMAZON_DYNAMODB_ENDPOINT");

	private String amazonAWSAccessKey = System.getenv("AMAZON_AWS_ACCESS_KEY");

	private String amazonAWSSecretKey = System.getenv("AMAZON_AWS_SECRET_KEY");

	private String basePackage = "reciter.database.dynamodb.model";

	@Value("${aws.dynamoDb.local.port}")
	private String dynamoDbLocalPort;

	@Value("${aws.dynamoDb.local.region}")
	private String dynamodbLocalRegion;

	@Value("${aws.dynamoDb.local.accesskey}")
	private String dynamodbLocalAccessKey;

	@Value("${aws.dynamoDb.local.secretkey}")
	private String dynamodbLocalSecretKey;

	@Value("${aws.dynamoDb.local.dbpath:}")
	private String dynamoDbPath;

	@Value("${aws.dynamoDb.local}")
	private boolean isDynamoDbLocal;

	@Value("${aws.dynamodb.settings.region}")
	private String dyanmodbRegion;

	@Value("${aws.dynamodb.settings.table.readcapacityunits}")
	private Long READ_CAPACITY_UNITS;

	@Value("${aws.dynamodb.settings.table.writecapacityunits}")
	private Long WRITE_CAPACITY_UNITS;

	@Value("${aws.dynamodb.settings.table.create}")
	private boolean createDynamoDbTable;

	@Value("${aws.dynamodb.settings.table.billingmode}")
	private BillingMode billingMode;
	
	@Value("${aws.dynamoDb.analysisOutput.table.name}")
	private String analysisOutputTableName;
	
	@Value("${aws.dynamoDb.analysisOutput.model.name}")
	private String analysisOutputModelName;
	
	
	@Bean
	public DynamoDbEnhancedClient dynamoDbEnhancedClient(DynamoDbClient dynamoDbClient) {
		return DynamoDbEnhancedClient.builder().dynamoDbClient(dynamoDbClient)
				 .extensions(AutoGeneratedTimestampRecordExtension.create(), AutoGeneratedUuidExtension.create())
				.build();
	}
	
	@Bean
	public DynamoDbClient dynamoDbClient() {
		DynamoDbClient dynamoDbClient = null;

		if (isDynamoDbLocal) {
			try {

				dynamoDbClient = DynamoDbClient.builder().httpClient(ApacheHttpClient.create())
						.endpointOverride(URI.create("http://localhost:" + dynamoDbLocalPort))
						//.endpointOverride(URI.create("http://dynamodb:" + dynamoDbLocalPort))
						//.endpointOverride(URI.create("http://host.docker.internal:" + dynamoDbLocalPort))
						
						.region(Region.of(dynamodbLocalRegion)) 
						.credentialsProvider(StaticCredentialsProvider.create(
								AwsBasicCredentials.create(dynamodbLocalAccessKey, dynamodbLocalSecretKey)))
						.build();

			} catch (Exception e) {
				log.error(e.getLocalizedMessage());
			}

		} else {
			if (StringUtils.isEmpty(dyanmodbRegion)) {
				throw new BeanCreationException(
						"""
						The aws.dynamodb.settings.region is not set in application.propeties file. 
						Please provide a valid  AWS region such as us-east-1 or eu-central-1. For list of valid regions
						 see - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html#Concepts.RegionsAndAvailabilityZones.Availability
						""");
			}

			dynamoDbClient = DynamoDbClient.builder().region(Region.of(dyanmodbRegion))
					.credentialsProvider(DefaultCredentialsProvider.create()).build();

		}
		if (dynamoDbClient != null) {
			if (createDynamoDbTable) {
				log.info("Creating all required dynamodb tables for ReCiter");
				createTables(dynamoDbClient);
			} else {
				log.info("Skipping table creation for dynamoDB.");
				log.warn(
						"This might cause issues with your application if tables are not created. Please set the aws.dynamodb.settings.table.create in application.properties as true if not already created.");
			}
		} else {
			log.info("aws.dynamoDb.local needs to have a boolean value set in application.propeties");
		}
		return dynamoDbClient;
	}

	// -------------------------------------------------------------------------
    // Table creation
    // -------------------------------------------------------------------------

    /**
     * Scans all {@code @DynamoDbBean} model classes and creates their tables if they do not exist.
     */
    private void createTables(DynamoDbClient dynamoDbClient) {

        ListTablesResponse listTablesResponse = dynamoDbClient.listTables();

        var scanner = new ClassPathScanningCandidateComponentProvider(false);
        scanner.addIncludeFilter(new AnnotationTypeFilter(DynamoDbBean.class));

        for (BeanDefinition bd : scanner.findCandidateComponents(basePackage)) {

            Class<?> clazz;
            try {
                clazz = Class.forName(bd.getBeanClassName());
            } catch (ClassNotFoundException e) {
                log.error("Could not load model class: {}", bd.getBeanClassName());
                continue;
            }

            // ------------------------------------------------------------------
            // Resolve table name
            // v1 used @DynamoDBTable(tableName="...") — v2 uses class simple name
            // Override for analysisOutput model if configured separately
            // ------------------------------------------------------------------
            String tableName = clazz.getSimpleName();
            if (tableName.equalsIgnoreCase(analysisOutputModelName)) {
                tableName = analysisOutputTableName;
            }

            if (listTablesResponse.tableNames().contains(tableName)) {
                log.info("DynamoDB table '{}' required for ReCiter is already created.", tableName);
                continue;
            }

            // ------------------------------------------------------------------
            // Resolve partition key
            // v1: @DynamoDBHashKey  →  v2: @DynamoDbPartitionKey
            // ------------------------------------------------------------------
            String partitionKeyName = findPartitionKeyName(clazz);
            if (partitionKeyName == null) {
                log.warn("Skipping table '{}': no @DynamoDbPartitionKey found on '{}'.",
                        tableName, bd.getBeanClassName());
                continue;
            }

            // ------------------------------------------------------------------
            // Resolve sort key
            // v1: @DynamoDBRangeKey  →  v2: @DynamoDbSortKey
            // ------------------------------------------------------------------
            SortKeyInfo sortKeyInfo = findSortKeyInfo(clazz);

            // ------------------------------------------------------------------
            // Build attribute definitions
            // ------------------------------------------------------------------
            List<AttributeDefinition> attributeDefinitions = new ArrayList<>();

            // Partition key — numeric for known tables, string for everything else
            ScalarAttributeType partitionKeyType = isNumericTable(tableName)
                    ? ScalarAttributeType.N
                    : ScalarAttributeType.S;

            attributeDefinitions.add(AttributeDefinition.builder()
                    .attributeName(partitionKeyName)
                    .attributeType(partitionKeyType)
                    .build());

            // Sort key attribute definition (only when present)
            if (sortKeyInfo != null) {
                attributeDefinitions.add(AttributeDefinition.builder()
                        .attributeName(sortKeyInfo.name())
                        .attributeType(sortKeyInfo.scalarType())
                        .build());
            }

            // ------------------------------------------------------------------
            // Build key schema
            // ------------------------------------------------------------------
            List<KeySchemaElement> keySchema = new ArrayList<>();
            keySchema.add(KeySchemaElement.builder()
                    .attributeName(partitionKeyName)
                    .keyType(KeyType.HASH)
                    .build());

            if (sortKeyInfo != null) {
                keySchema.add(KeySchemaElement.builder()
                        .attributeName(sortKeyInfo.name())
                        .keyType(KeyType.RANGE)
                        .build());
            }

            // ------------------------------------------------------------------
            // Build and execute CreateTableRequest
            // ------------------------------------------------------------------
            CreateTableRequest.Builder requestBuilder = CreateTableRequest.builder()
                    .tableName(tableName)
                    .keySchema(keySchema)
                    .attributeDefinitions(attributeDefinitions);

            if (billingMode == BillingMode.PAY_PER_REQUEST) {
                requestBuilder.billingMode(BillingMode.PAY_PER_REQUEST);
            } else if (billingMode == BillingMode.PROVISIONED) {
                requestBuilder
                        .billingMode(BillingMode.PROVISIONED)
                        .provisionedThroughput(ProvisionedThroughput.builder()
                                .readCapacityUnits(READ_CAPACITY_UNITS)
                                .writeCapacityUnits(WRITE_CAPACITY_UNITS)
                                .build());
            }

            dynamoDbClient.createTable(requestBuilder.build());

            log.info("Waiting for DynamoDB table '{}' to become ACTIVE in AWS.", tableName);
            try {
                waitUntilTableActive(dynamoDbClient, tableName);
            } catch (Exception e) {
                log.error("Error waiting for table '{}': {}", tableName, e.getMessage());
            }
            log.info("DynamoDB table '{}' has been successfully created in AWS.", tableName);
        }
    }

    // -------------------------------------------------------------------------
    // Helper — wait for ACTIVE
    // -------------------------------------------------------------------------

    private void waitUntilTableActive(DynamoDbClient dynamoDbClient, String tableName)
            throws InterruptedException {

        int attempts   = 0;
        int maxAttempts = 60;

        while (attempts < maxAttempts) {
            try {
                DescribeTableResponse response = dynamoDbClient.describeTable(
                        DescribeTableRequest.builder().tableName(tableName).build());

                if (response.table().tableStatus() == TableStatus.ACTIVE) {
                    return;
                }
            } catch (DynamoDbException e) {
                log.warn("Error checking status of table '{}': {}", tableName, e.getMessage());
            }
            Thread.sleep(1000);
            attempts++;
        }

        throw new RuntimeException(
                "Table '%s' never became ACTIVE after %d seconds.".formatted(tableName, maxAttempts));
    }

    // -------------------------------------------------------------------------
    // Helper — find partition key name
    // v1: @DynamoDBHashKey  →  v2: @DynamoDbPartitionKey
    // -------------------------------------------------------------------------

    private String findPartitionKeyName(Class<?> clazz) {

        // 1. Check fields first
        for (Field field : clazz.getDeclaredFields()) {
            if (field.isAnnotationPresent(DynamoDbPartitionKey.class)) {
                // Honour @DynamoDbAttribute override if present
                if (field.isAnnotationPresent(DynamoDbAttribute.class)) {
                    String attrName = field.getAnnotation(DynamoDbAttribute.class).value();
                    return StringUtils.isNotEmpty(attrName) ? attrName : field.getName();
                }
                return field.getName();
            }
        }

        // 2. Fallback: check getter methods
        for (Method method : clazz.getDeclaredMethods()) {
            if (method.isAnnotationPresent(DynamoDbPartitionKey.class)
                    && method.getName().startsWith("get")
                    && method.getParameterCount() == 0) {

                if (method.isAnnotationPresent(DynamoDbAttribute.class)) {
                    String attrName = method.getAnnotation(DynamoDbAttribute.class).value();
                    return StringUtils.isNotEmpty(attrName) ? attrName : deriveFieldName(method.getName());
                }
                return deriveFieldName(method.getName());
            }
        }

        return null;
    }

    // -------------------------------------------------------------------------
    // Helper — find sort key info
    // v1: @DynamoDBRangeKey  →  v2: @DynamoDbSortKey
    // -------------------------------------------------------------------------

    /**
     * Holds all info needed to define the sort key attribute and key-schema element.
     * Java 17 record replaces a plain data holder class.
     */
    private record SortKeyInfo(String name, ScalarAttributeType scalarType) {}

    
    private SortKeyInfo findSortKeyInfo(Class<?> clazz) {
    	 
        for (Method method : clazz.getDeclaredMethods()) {
            if (!method.getName().startsWith("get") || method.getParameterCount() != 0) {
                continue;
            }
 
            // Check for @DynamoDbSortKey by iterating annotations — avoids the
            // isAnnotationPresent(DynamoDbSortKey.class) compile-time @Target error
            boolean hasSortKey = false;
            for (java.lang.annotation.Annotation annotation : method.getAnnotations()) {
                if (annotation.annotationType().equals(DynamoDbSortKey.class)) {
                    hasSortKey = true;
                    break;
                }
            }
            if (!hasSortKey) {
                continue;
            }
 
            // Resolve attribute name: prefer @DynamoDbAttribute, else derive from getter
            String attrName = null;
            if (method.isAnnotationPresent(DynamoDbAttribute.class)) {
                attrName = method.getAnnotation(DynamoDbAttribute.class).value();
            }
            String sortKeyName = StringUtils.isNotEmpty(attrName)
                    ? attrName
                    : deriveFieldName(method.getName());
 
            // Resolve Java type: check backing field first (most accurate),
            // fall back to getter return type
            String backingFieldName = deriveFieldName(method.getName());
            Class<?> javaType = resolveFieldType(clazz.getDeclaredFields(), backingFieldName);
            if (javaType == null) {
                javaType = method.getReturnType();
            }
 
            return new SortKeyInfo(sortKeyName, toScalarType(javaType));
        }
 
        return null; // no sort key on this model
    }

    // -------------------------------------------------------------------------
    // Utilities
    // -------------------------------------------------------------------------

    /** Returns true for tables whose partition key is numeric (N). */
    private boolean isNumericTable(String tableName) {
        return tableName.equalsIgnoreCase("ScienceMetrixDepartmentCategory")
                || tableName.equalsIgnoreCase("ScienceMetrix")
                || tableName.equalsIgnoreCase("PubMedArticle");
    }

    /**
     * Maps a Java type to a DynamoDB {@link ScalarAttributeType}.
     * Numeric primitives/wrappers → N, everything else → S.
     */
    private ScalarAttributeType toScalarType(Class<?> javaType) {
        if (javaType == long.class  || javaType == Long.class
                || javaType == int.class   || javaType == Integer.class
                || javaType == double.class || javaType == Double.class
                || javaType == float.class  || javaType == Float.class
                || javaType == short.class  || javaType == Short.class) {
            return ScalarAttributeType.N;
        }
        return ScalarAttributeType.S;
    }

    /** Converts a getter name (e.g. {@code getName}) to a field name ({@code name}). */
    private String deriveFieldName(String getterName) {
        // strip "get" prefix and lower-case the first character
        return Character.toLowerCase(getterName.charAt(3)) + getterName.substring(4);
    }
    
    /**
     * Looks up the declared field matching {@code fieldName} and returns its type.
     * Accepts a {@code Field[]} array (not {@code Class<?>}) to avoid the
     * captured-wildcard compiler error on {@code Class<?>.getDeclaredFields()}.
     * Returns {@code null} if no matching field is found.
     */
    private Class<?> resolveFieldType(Field[] fields, String fieldName) {
        for (Field field : fields) {
            if (field.getName().equals(fieldName)) {
                return field.getType();
            }
        }
        return null;
    }
}
