package reciter.database.dynamodb;

import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.BeanCreationException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.type.filter.AnnotationTypeFilter;

import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.http.apache.ApacheHttpClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.model.AttributeDefinition;
import software.amazon.awssdk.services.dynamodb.model.BillingMode;
import software.amazon.awssdk.services.dynamodb.model.CreateTableRequest;
import software.amazon.awssdk.services.dynamodb.model.DescribeTableRequest;
import software.amazon.awssdk.services.dynamodb.model.DescribeTableResponse;
import software.amazon.awssdk.services.dynamodb.model.DynamoDbException;
import software.amazon.awssdk.services.dynamodb.model.KeySchemaElement;
import software.amazon.awssdk.services.dynamodb.model.KeyType;
import software.amazon.awssdk.services.dynamodb.model.ListTablesResponse;
import software.amazon.awssdk.services.dynamodb.model.ProvisionedThroughput;
import software.amazon.awssdk.services.dynamodb.model.ScalarAttributeType;
import software.amazon.awssdk.services.dynamodb.model.TableStatus;

@Configuration
public class DynamoDbConfig {
	
	private static final Logger log = LoggerFactory.getLogger(DynamoDbConfig.class);

	private String amazonDynamoDBEndpoint = System.getenv("AMAZON_DYNAMODB_ENDPOINT");

	private String amazonAWSAccessKey = System.getenv("AMAZON_AWS_ACCESS_KEY");

	private String amazonAWSSecretKey = System.getenv("AMAZON_AWS_SECRET_KEY");

	private String basePackage = "reciter.database.dynamodb.model";

	@Value("${aws.dynamoDb.local.port}")
	private String dynamoDbLocalPort;

	@Value("${aws.dynamoDb.local.region}")
	private String dynamodbLocalRegion;

	@Value("${aws.dynamoDb.local.accesskey}")
	private String dynamodbLocalAccessKey;

	@Value("${aws.dynamoDb.local.secretkey}")
	private String dynamodbLocalSecretKey;

	@Value("${aws.dynamoDb.local.dbpath:}")
	private String dynamoDbPath;

	@Value("${aws.dynamoDb.local}")
	private boolean isDynamoDbLocal;

	@Value("${aws.dynamodb.settings.region}")
	private String dynamodbRegion;

	@Value("${aws.dynamodb.settings.table.readcapacityunits}")
	private Long READ_CAPACITY_UNITS;

	@Value("${aws.dynamodb.settings.table.writecapacityunits}")
	private Long WRITE_CAPACITY_UNITS;

	@Value("${aws.dynamodb.settings.table.create}")
	private boolean createDynamoDbTable;

	@Value("${aws.dynamodb.settings.table.billingmode}")
	private BillingMode billingMode;
	
	@Value("${aws.dynamoDb.analysisOutput.table.name}")
	private String analysisOutputTableName;
	
	@Value("${aws.dynamoDb.analysisOutput.model.name}")
	private String analysisOutputModelName;
	
	
	@Bean
	public DynamoDbEnhancedClient dynamoDbEnhancedClient(DynamoDbClient dynamoDbClient) {
		return DynamoDbEnhancedClient.builder().dynamoDbClient(dynamoDbClient)
				 .extensions(AutoGeneratedTimestampRecordExtension.create(), AutoGeneratedUuidExtension.create(),new LegacyS3AttributeExtension())
				.build();
	}
	
	@Bean
	public DynamoDbClient dynamoDbClient() {
		DynamoDbClient dynamoDbClient = null;

		if (isDynamoDbLocal) {
			try {

				dynamoDbClient = DynamoDbClient.builder().httpClient(ApacheHttpClient.create())
						.endpointOverride(URI.create("http://localhost:" + dynamoDbLocalPort))
						//.endpointOverride(URI.create("http://dynamodb:" + dynamoDbLocalPort))
						//.endpointOverride(URI.create("http://host.docker.internal:" + dynamoDbLocalPort))
						
						.region(Region.of(dynamodbLocalRegion)) 
						.credentialsProvider(StaticCredentialsProvider.create(
								AwsBasicCredentials.create(dynamodbLocalAccessKey, dynamodbLocalSecretKey)))
						.build();

			} catch (Exception e) {
				log.error(e.getLocalizedMessage());
			}

		} else {
			if (StringUtils.isEmpty(dynamodbRegion)) {
				throw new BeanCreationException(
						"""
						The aws.dynamodb.settings.region is not set in application.propeties file. 
						Please provide a valid  AWS region such as us-east-1 or eu-central-1. For list of valid regions
						 see - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html#Concepts.RegionsAndAvailabilityZones.Availability
						""");
			}

			dynamoDbClient = DynamoDbClient.builder().region(Region.of(dynamodbRegion))
					.credentialsProvider(DefaultCredentialsProvider.create()).build();

		}
		if (dynamoDbClient != null) {
			if (createDynamoDbTable) {
				log.info("Creating all required dynamodb tables for ReCiter");
				createTables(dynamoDbClient);
			} else {
				log.info("Skipping table creation for dynamoDB.");
				log.warn(
						"This might cause issues with your application if tables are not created. Please set the aws.dynamodb.settings.table.create in application.properties as true if not already created.");
			}
		} else {
			log.info("aws.dynamoDb.local needs to have a boolean value set in application.propeties");
		}
		return dynamoDbClient;
	}

    /**
     * Scans all {@code @DynamoDbBean} model classes and creates their tables if they do not exist.
     */
	@SuppressWarnings("unchecked")
	private void createTables(DynamoDbClient dynamoDbClient) {

	    ListTablesResponse listTablesResponse = dynamoDbClient.listTables();

	    var scanner = new ClassPathScanningCandidateComponentProvider(false);
	    scanner.addIncludeFilter(new AnnotationTypeFilter(DynamoDbBean.class));

	    for (BeanDefinition bd : scanner.findCandidateComponents(basePackage)) {

	        Class<?> clazz;
	        try {
	            clazz = Class.forName(bd.getBeanClassName());
	        } catch (ClassNotFoundException e) {
	            log.error("Could not load model class: {}", bd.getBeanClassName());
	            continue;
	        }

	        // Resolve table name — override for analysisOutput model if configured
	        String tableName = clazz.getSimpleName();
	        if (tableName.equalsIgnoreCase(analysisOutputModelName)) {
	            tableName = analysisOutputTableName;
	        }

	        if (listTablesResponse.tableNames().contains(tableName)) {
	            log.info("DynamoDB table '{}' required for ReCiter is already created.", tableName);
	            continue;
	        }

	        // ------------------------------------------------------------------
	        // Use TableSchema.fromBean() to resolve key names.
	        // This is the ONLY reliable approach in SDK v2 — it uses the same
	        // internal logic the Enhanced Client uses at runtime, so the names
	        // returned here are guaranteed to match what UpdateItem/GetItem send.
	        // Avoids all @DynamoDbSortKey reflection/compile issues entirely.
	        // ------------------------------------------------------------------
	        TableSchema<?> tableSchema;
	        String partitionKeyName;
	        java.util.Optional<String> sortKeyOpt;
	        try {
	            tableSchema = TableSchema.fromBean((Class) clazz);
	            // primaryPartitionKey() throws IllegalArgumentException if no @DynamoDbPartitionKey
	            // is found on any getter — catch it and skip the class gracefully
	            partitionKeyName = tableSchema.tableMetadata().primaryPartitionKey();
	            sortKeyOpt = tableSchema.tableMetadata().primarySortKey();
	        } catch (IllegalArgumentException e) {
	            log.warn("Skipping table '{}': no primary key defined in TableSchema ({}). "
	                    + "Ensure @DynamoDbPartitionKey is on a getter method, not a field.",
	                    tableName, e.getMessage());
	            continue;
	        } catch (Exception e) {
	            log.warn("Could not build TableSchema for '{}': {} — skipping.", tableName, e.getMessage());
	            continue;
	        }
	        // Build attribute definitions
	        List<AttributeDefinition> attributeDefinitions = new ArrayList<>();
	        attributeDefinitions.add(AttributeDefinition.builder()
	                .attributeName(partitionKeyName)
	                .attributeType(isNumericTable(tableName) ? ScalarAttributeType.N : ScalarAttributeType.S)
	                .build());

	        sortKeyOpt.ifPresent(sortKeyName ->
	            attributeDefinitions.add(AttributeDefinition.builder()
	                    .attributeName(sortKeyName)
	                    .attributeType(isNumericSortKey(sortKeyName) ? ScalarAttributeType.N : ScalarAttributeType.S)
	                    .build())
	        );

	        // Build key schema
	        List<KeySchemaElement> keySchema = new ArrayList<>();
	        keySchema.add(KeySchemaElement.builder()
	                .attributeName(partitionKeyName)
	                .keyType(KeyType.HASH)
	                .build());

	        sortKeyOpt.ifPresent(sortKeyName ->
	            keySchema.add(KeySchemaElement.builder()
	                    .attributeName(sortKeyName)
	                    .keyType(KeyType.RANGE)
	                    .build())
	        );

	        // Build CreateTableRequest
	        CreateTableRequest.Builder requestBuilder = CreateTableRequest.builder()
	                .tableName(tableName)
	                .keySchema(keySchema)
	                .attributeDefinitions(attributeDefinitions);

	        if (billingMode == BillingMode.PAY_PER_REQUEST) {
	            requestBuilder.billingMode(BillingMode.PAY_PER_REQUEST);
	        } else if (billingMode == BillingMode.PROVISIONED) {
	            requestBuilder
	                    .billingMode(BillingMode.PROVISIONED)
	                    .provisionedThroughput(ProvisionedThroughput.builder()
	                            .readCapacityUnits(READ_CAPACITY_UNITS)
	                            .writeCapacityUnits(WRITE_CAPACITY_UNITS)
	                            .build());
	        }

	        dynamoDbClient.createTable(requestBuilder.build());

	        log.info("Waiting for DynamoDB table '{}' to become ACTIVE in AWS.", tableName);
	        try {
	            waitUntilTableActive(dynamoDbClient, tableName);
	        } catch (Exception e) {
	            log.error("Error waiting for table '{}': {}", tableName, e.getMessage());
	        }
	        log.info("DynamoDB table '{}' has been successfully created in AWS.", tableName);
	    }
	}
	/**
	 * Sort key attributes stored as Number (N) in DynamoDB.
	 * articleId is String in ArticleProvenance — NOT listed here.
	 */
	private boolean isNumericSortKey(String attributeName) {
	    return "pmid".equalsIgnoreCase(attributeName);
	}

    private void waitUntilTableActive(DynamoDbClient dynamoDbClient, String tableName)
            throws InterruptedException {

        int attempts   = 0;
        int maxAttempts = 60;

        while (attempts < maxAttempts) {
            try {
                DescribeTableResponse response = dynamoDbClient.describeTable(
                        DescribeTableRequest.builder().tableName(tableName).build());

                if (response.table().tableStatus() == TableStatus.ACTIVE) {
                    return;
                }
            } catch (DynamoDbException e) {
                log.warn("Error checking status of table '{}': {}", tableName, e.getMessage());
            }
            Thread.sleep(1000);
            attempts++;
        }

        throw new RuntimeException(
                "Table '%s' never became ACTIVE after %d seconds.".formatted(tableName, maxAttempts));
    }

    /** Returns true for tables whose partition key is numeric (N). */
    private boolean isNumericTable(String tableName) {
        return tableName.equalsIgnoreCase("ScienceMetrixDepartmentCategory")
                || tableName.equalsIgnoreCase("ScienceMetrix")
                || tableName.equalsIgnoreCase("PubMedArticle");
    }

}